apiVersion: v1
kind: Service
metadata:
  name: stream-backend-svc
  namespace: bestream
spec:
  selector:
    app: stream-backend
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: LoadBalancer
