apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-frontend-deployment
  namespace: frontend
  labels:
    app: streaming-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-frontend
  template:
    metadata:
      labels:
        app: streaming-frontend
    spec:
      containers:
      - name: streaming-frontend-container
        image: ravikishans/streamingapp:frontend
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-config
