apiVersion: v1
kind: Service
metadata:
  name: streaming-frontend-svc
  namespace: frontend
spec:
  selector:
    app: streaming-frontend
  ports:
  - protocol: TCP
    port: 9099
    targetPort: 3000
  type: LoadBalancer
