apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: 975050024946.dkr.ecr.us-west-1.amazonaws.com/dineshb14-streamingapp-chat:v1
        ports:
        - containerPort: 3004
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "3004"
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: streamingapp-config
              key: MONGO_URI
        - name: CLIENT_URLS
          valueFrom:
            configMapKeyRef:
              name: streamingapp-config
              key: CLIENT_URLS
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: streamingapp-secret
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: chat
  ports:
  - port: 3004
    targetPort: 3004
  type: ClusterIP