apiVersion: v1
kind: Service
metadata:
  name: auth-backend-svc
  namespace: beauth
spec:
  selector:
    app: auth-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: LoadBalancer
