apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.frontend.namespace }}
data:
  AWS_IP: {{ .Values.frontend.data.AWS_IP }}
  STREAM_PORT: {{ .Values.frontend.data.STREAM_PORT | quote }}
