apiVersion: v1
kind: Secret
metadata:
  name: auth-backend-secrets
  namespace: {{ .Values.auth_service.namespace }}
type: Opaque
data:
  MONGO_URI: {{ .Values.auth_service.spec.containers.env.MONGO_URI | b64enc }}


---

apiVersion: v1
kind: Secret
metadata:
  name: stream-backend-secrets
  namespace: {{ .Values.streaming_service.namespace }}
type: Opaque
data:
  MONGO_URI: {{ .Values.streaming_service.spec.containers.env.MONGO_URI | b64enc }}
